name: "Watch Post (スマホOK)"
description: "コレクションを記事化するフォーム（スマホ用）"
title: "[新規投稿] タイトルを入力してください"
labels: ["post"]

body:
  - type: input
    id: model
    attributes:
      label: "モデル名（例: Cyma Time-O-Vox 18K Chronomètre）"
      placeholder: "例）Cyma Time-O-Vox 18K Chronomètre"
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: "概要（1〜2行で）"
      placeholder: "例）1950年代製 18K 金無垢 クロノメーター仕様のアラームウォッチ"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "詳細説明"
      placeholder: "技術・背景・魅力などを自由に記入してください（Markdown対応）"
    validations:
      required: true

  - type: textarea
    id: specs
    attributes:
      label: "スペック"
      placeholder: "ケース径: 35mm\nムーブメント: Cal.R.464\n素材: 18K Gold\n機能: アラーム・時分秒"
    validations:
      required: false

  - type: textarea
    id: images
    attributes:
      label: "画像リンク"
      placeholder: "例）Google Drive / Imgur / GitHub Upload のURLを貼ってください"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "備考"
      placeholder: "メモや補足があれば自由に記入してください"
    validations:
      required: false
