name: "Watch Post (スマホOK)"
description: "コレクションを記事化するフォーム"
title: "[新規投稿] タイトルを入力してください"
labels:
  - post

body:
  - type: input
    id: title
    attributes:
      label: モデル名
      description: 例: Cyma Time-O-Vox 18K Chronomètre
      placeholder: 入力してください
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: ブランド・キャリバー・素材など
      placeholder: ブランド、モデル、素材、キャリバー...
    validations:
      required: true

  - type: textarea
    id: photos
    attributes:
      label: 写真
      description: 画像をここにアップロードしてください

  - type: textarea
    id: comment
    attributes:
      label: オーナーコメント
      description: 自由に一言をどうぞ
