name: Watch Post (スマホOK)
description: 写真を貼って各項目を入力すると、投稿ページが自動生成されます
title: "[POST] ブランド / モデル名 をここに"
labels: ["publish"]
assignees: []
body:
  - type: input
    id: brand_model
    attributes:
      label: ブランド／モデル名
      placeholder: "CYMA Time-O-Vox Chronomètre 18K"
    validations: { required: true }

  - type: input
    id: caliber
    attributes:
      label: キャリバー
      placeholder: "R.464"
    validations: { required: true }

  - type: dropdown
    id: winding
    attributes:
      label: 巻き上げ方式
      options: ["手巻き","自動巻き","クォーツ"]
    validations: { required: true }

  - type: input
    id: material
    attributes:
      label: ケース素材
      placeholder: "18K イエローゴールド"
    validations: { required: true }

  - type: input
    id: case
    attributes:
      label: ケース径（mm）
      placeholder: "35"
    validations: { required: true }

  - type: input
    id: lug
    attributes:
      label: ラグ幅（mm）
      placeholder: "18"
    validations: { required: true }

  - type: input
    id: year
    attributes:
      label: 製造年代
      placeholder: "1950年代中期"
    validations: { required: true }

  - type: checkboxes
    id: complications
    attributes:
      label: 機能（複数可）
      options:
        - label: アラーム
        - label: GMT
        - label: クロノグラフ
        - label: トリプルカレンダー
        - label: アニュアル/パーペチュアル
        - label: ミニッツリピーター
        - label: ムーンフェイズ
        - label: パワーリザーブ
        - label: その他あり（本文に追記）
    validations: { required: false }

  - type: textarea
    id: photos
    attributes:
      label: 写真（5枚まで推奨）
      description: "スマホからそのまま **画像を貼り付け** してください（![](...) が本文に入ります）。Drive/URLでもOK。最初の1枚がメインになります。"
      placeholder: "ここに画像をペースト or URLを改行で複数"
    validations: { required: true }

  - type: input
    id: video
    attributes:
      label: 動画URL（任意）
      placeholder: "YouTube / Google Drive など"

  - type: input
    id: tagline
    attributes:
      label: キャッチコピー（1行）
      placeholder: "鳴るクロノメーター、6秒の神経"
    validations: { required: true }

  - type: input
    id: owner
    attributes:
      label: 展示者名（任意）
      placeholder: "ハンドルネーム"

  - type: textarea
    id: comment
    attributes:
      label: 自由コメント（魅力中心）
      placeholder: "魅力に全振りで。修理や不具合は書かない。200〜400字目安。"
    validations: { required: true }

  - type: input
    id: provenance
    attributes:
      label: 仕入れ経路（任意）
      placeholder: "Chrono24経由 Plus Ultra"

  - type: textarea
    id: condition
    attributes:
      label: 状態（任意）
      placeholder: "例：軽度の経年、文字盤ヤレ心地よし"

  - type: textarea
    id: notes
    attributes:
      label: 特記事項（任意）
      placeholder: "例：CYMAflexの仕様メモ等"

  - type: input
    id: last_service
    attributes:
      label: 最終整備歴（任意）
      placeholder: "例：2025年OH依頼中"

  - type: input
    id: next_service
    attributes:
      label: 次回OH推奨時期（任意）
      placeholder: "例：2030年頃"

  - type: textarea
    id: extra
    attributes:
      label: その他（任意）
      placeholder: "SNSリンク／参考価格レンジ等"
